version: '3.4'

services:
  hugin:
    image: ${DOCKER_REGISTRY-}hugin
    ports:
    - 8080:8080
    build:
      context: .
      dockerfile: Hugin/Dockerfile
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      DB_CONNECTION_STR: "Host=db; Database=hugin-dev; Port=5432; Username=hugin; Password=password"
      APP_SECRET_KEY: "your-secret-key(need-32-characters)"
      APP_DATA_PATH: /app-data
      APP_NAME: Hugin
      APP_DESCRIPTION: ""
      
      ### for Development
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      APP_URL: http://localhost:8080
      
      ### for LDAP
      LDAP_HOST: uni-ldap1.db.tokushima-u.ac.jp
      LDAP_PORT: 636
      LDAP_BASE: dc=tokushima-u,dc=ac,dc=jp
      LDAP_ID_ATTR: uid
      LDAP_MAIL_ATTR: mail
      LDAP_NAME_ATTR: displayName;lang-ja
      LDAP_ENGNAME_ATTR: displayName

    volumes:
    - app-data:/app-data
    cap_add:
    - SYS_ADMIN
    networks:
    - nw-hugin-dev
    depends_on:
    - db

  db:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hugin-dev
      POSTGRES_USER: hugin
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
    - nw-hugin-dev

networks:
  nw-hugin-dev:
    driver: bridge

volumes:
  app-data:
    driver: local
  db-data:
    driver: local
