version: '3.4'

services:
  hugin:
    image: hugin-local
    ports:
    - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      DB_CONNECTION_STR: "Host=db; Database=hugin-local; Port=5432; Username=hugin; Password=password"
      APP_SECRET_KEY: "your-secret-key(need-32-characters)"
      APP_DATA_PATH: /app-data
      APP_NAME: Hugin
      APP_DESCRIPTION: ""
           
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      APP_URL: http://localhost:8080


    volumes:
    - app-data:/app-data
    cap_add:
    - SYS_ADMIN
    networks:
    - nw-hugin-local
    depends_on:
    - db

  db:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hugin-local
      POSTGRES_USER: hugin
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
    - nw-hugin-local

networks:
  nw-hugin-local:
    driver: bridge

volumes:
  app-data:
    driver: local
  db-data:
    driver: local
